#! /bin/bash
# Creates a samba user account with the provided username and a random password
# that must be changed the before the user can login.

if [ $# -eq 0 ]
    then
    echo "usage: smbadduser [username]"
else
    user=$1
    password=$(tr -dc A-Za-z0-9_ < /dev/urandom | head -c 8 | xargs)
    response=$((echo $password; echo $password) | sudo smbpasswd -as $user)

    if [ "$response" == "Added user $user." ]
        then
        echo "Added user $user."
    elif [ "$response" == "" ]
        then
        echo "Changed password for user $user."
    else
        echo "Invalid username."
    fi

    if [ "$response" == "Added user $user." ] || [ "$response" == "" ]
        then
        echo "Temporary password is $password"
        foo=$(sudo net sam set pwdmustchangenow $user yes)
        echo "User must change password at next login."
    fi
fi
